### ISSUE TITLE
Constraints on installing pip packages?

### ISSUE THREAD

**Issue by Tushar-N** [Cloud-CV/EvalAI-Starters#53]
I'm trying to add [this package](https://github.com/gfairchild/pyxDamerauLevenshtein) as a requirement for evaluation. I uncommented the code [here](https://github.com/Cloud-CV/EvalAI-Starters/blob/820dc9ef66316ac0946a5c08e89b1d31c2b2de49/evaluation_script/__init__.py#L36) that calls `pip install <package>`but I get the following error on the worker log when I try and submit. Are there some packages that can't be installed this way? 

```
Collecting pyxdameraulevenshtein
Downloading https://files.pythonhosted.org/packages/aa/e8/53d212009d6d40fdd98ef41585e5442812323d145aa47f507996093567f2/pyxDamerauLevenshtein-1.7.0.tar.gz
Installing build dependencies: started
[2022-02-03 18:44:29] ERROR WORKER_LOG Exception raised while creating Python module for challenge_id: 1542
Traceback (most recent call last):
File "/code/scripts/workers/submission_worker.py", line 321, in extract_challenge_data
CHALLENGE_IMPORT_STRING.format(challenge_id=challenge.id)
File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/tmp/tmpclumagos/compute/challenge_data/challenge_1542/__init__.py", line 73, in <module>
install("pyxdameraulevenshtein")
File "/tmp/tmpclumagos/compute/challenge_data/challenge_1542/__init__.py", line 54, in install
subprocess.check_call([sys.executable, "-m", "pip", "install", package])
File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', 'install', 'pyxdameraulevenshtein']' died with <Signals.SIGKILL: 9>.
```

**Comment by Kilichbek** [comment]
Hello, the same issue is popping up in my challenge
